#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += aeon_nt35521_hd720_dsi_vdo_f509_xingliangda.o


ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc


