#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_FINGERPRINT_GT368) += gx368/
obj-$(CONFIG_FINGERPRINT_GT368_OTP) += gx368_otp/
obj-$(CONFIG_FINGERPRINT_GT368_OTP_X32) += gx368_otp_x32/
obj-$(CONFIG_FINGERPRINT_MICROARRAY) += microarray/
