#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += aeon_ili9881c_hd720_dsi_vdo_f509_xiaozhixing.o


ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc


